CONNECTION_ACK = b'0011'  # sends: <CLIENT_ID>
USER_COUNT = b'0010'  # sends: <NUMBER OF USERS IN THE ROOM>
START = b'1111'

SPAWN_CHIP = b'1000'  # sends: <CHIP LOCATION>  <CHIP TYPE> <CHIP ID>
CHIP_POS_UPDATE = b'1110'  # sends: <CHIP LOCATION>  <CHIP TYPE> <CHIP ID> <CHIP STATE>

ANNOUNCE_WINNER = b'0100'  # sends: <WINNER CLIENT ID>
